### ISSUE TITLE
[Editor] Project list ONLY show projects created inside the default project folder

### ISSUE THREAD

**Issue by brmassa** [ProwlEngine/Prowl#144]
**Describe the bug**
 If a project is created inside other folder but the default project folder defined by Prowl, it will not show 

**To Reproduce**
1. Open Prowl
2. Create a new project, but select "C:\MyProjects\project-1"
3. click ok
4. The project is not displayed in the project screen

**Expected behavior**
list any project created, despite the path.

**Comment by PaperPrototype** [comment]
I believe @sinnwrig recently implemented a fix for this in the new development branch of prowl

**Comment by brmassa** [comment]
oh.... i did not know that ``development` branch was being used instead `main`. I will test it then

**Comment by PaperPrototype** [comment]
@brmassa it is completely different FYI and many things are still broken

**Comment by brmassa** [comment]
I've noticed

**Comment by brmassa** [comment]
I've noticed some Vulkan implementation.

**Comment by brmassa** [comment]
I've noticed some Vulkan implementation.

1. What other big changes from main? (I can run a diff, but 460 commits is a lot to cover)
1. Couldn't we merge specific enhancements/bugfixes more granularly into `main` (like the launcher overhaul)?
1. Do the devs use Discord/Matrix regularly to discuss? Or is it more focused towards end users?

I'm a senior C# dev and would like to help.

**Comment by PaperPrototype** [comment]
@brmassa as far as I know most development discussions are through the official Discord via Video chat (almost daily)

**Comment by michaelsakharov** [comment]
Hey!
Yeah, the development branch was originally called Veldrid and was just the port of the engine from Silk.net OpenGL, to Veldrid to support more graphics backends like Vulkan, DirectX, and Metal.
But In the process, a lot of other random things got improved/changed so we recently renamed it to "Development"
We're planning to merge it back into the main branch once the graphics functionality is on par with the previous version or at least close to it.

We are quite active on Discord. We often discuss and work on Prowl in voice channels, but we also have a dedicated text channel for contributors if you prefer that.
