### ISSUE TITLE
Enable issue tracking for Prowl.Veldrid and Prowl.DotRecast

### ISSUE THREAD

**Issue by brmassa** [ProwlEngine/Prowl#162]
Since both projects are forked and maintained separately, I suggest enabling it on both projects.

GitHub normally disable issue tracking on forked projects. Simple toggle on Settings.

**Comment by brmassa** [comment]
Also, would be interesting to enable the Discord (and/or Matrix) bot to also monitor them (if not already).

**Comment by sinnwrig** [comment]
(As of now) Issue tracking should be enabled on all ProwlEngine repositories.
