### ISSUE TITLE
Prowl Manual/Guides

### ISSUE THREAD

**Issue by PaperPrototype** [ProwlEngine/Prowl#176]
**Is your feature request related to a problem? Please describe.**
I am having trouble keeping up with all the new changes and how they work. It would be nice to have somewhere we can internally document Prowl and all the features we are adding.
eg. 
- Command Line arguments for prowl #151 (including headless mode and it's CLI args), 
- how to create a gameObject, 
- how to create a shader, 
- how to use the UI. 

**Describe the solution you'd like**
inside of the Prowl repository I can make a `manual/` or `doc/` or `guides/` directory with `.md` files that deploy as a VitePress site and have it automatically publish any pushes to development and main (with separate sites for each branch)

**Describe alternatives you've considered**
We are already considering using docfx for API docs **but** a _manual_ with guides documenting non-API related things would be nice.

**Additional context**
VitePress site Currently at https://prowl.pages.dev

**Comment by PaperPrototype** [comment]
Oh we also currently have some gitbook docs, but it looks like they are unused atm

**Comment by michaelsakharov** [comment]
This is the same as the create docs one :P there's no docs yet and won't be for a little while. I would also rather the docs be in another repo.

Can you move this to be a comment to the other issue?
